import { useEffect, useMemo, useState } from 'react';
import FSM from '@trigo/fsm';
import ReactExport from 'react-data-to-export';

const { ExcelFile } = ReactExport;
const ExcelSheet = ExcelFile.ExcelSheet;
const ExcelColumn = ExcelFile.ExcelColumn;

const packageRows = [
  { name: '@posthog/icons', role: 'UI glyphs' },
  { name: '@voiceflow/react-chat', role: 'Assistant widget' },
  { name: '@trigo/fsm', role: 'State machine' },
  { name: 'react-data-to-export', role: 'Download button' }
];

export default function App() {
  const [workflowState, setWorkflowState] = useState('discovery');
  const [voiceflowExports, setVoiceflowExports] = useState([]);
  const [iconInfo, setIconInfo] = useState({ name: '', Component: null });

  const workflow = useMemo(
    () =>
      new FSM({
        initialState: 'discovery',
        transitions: [
          { name: 'plan', from: 'discovery', to: 'planning' },
          { name: 'report', from: 'planning', to: 'reporting' }
        ],
        data: {}
      }),
    []
  );

  useEffect(() => {
    import('@voiceflow/react-chat')
      .then((module) => {
        setVoiceflowExports(Object.keys(module).slice(0, 6));
      })
      .catch((error) => {
        setVoiceflowExports([`Unable to load: ${error.message}`]);
      });
  }, []);

  useEffect(() => {
    import('@posthog/icons')
      .then((icons) => {
        const candidates = Object.entries(icons).filter(
          ([, value]) => typeof value === 'function'
        );
        if (candidates.length) {
          const [name, Component] = candidates[0];
          setIconInfo({ name, Component });
        }
      })
      .catch((error) => {
        setIconInfo({ name: `Load failure: ${error.message}` });
      });
  }, []);

  const nextStep = () => {
    if (workflow.state === 'discovery') {
      workflow.plan();
    } else if (workflow.state === 'planning') {
      workflow.report();
    }
    setWorkflowState(workflow.state);
  };

  const excelData = packageRows.map((row) => ({
    ...row,
    state: workflowState
  }));

  return (
    <div style={styles.shell}>
      <header style={styles.header}>
        <div>
          <p style={styles.kicker}>Demo UI</p>
          <h1 style={styles.title}>Safe Package Explorer</h1>
          <p style={styles.subtitle}>
            React UI that touches the same dependency set as the CLI, showcasing
            icons, FSM-driven flow, Voiceflow metadata, and an Excel export
            generated by <code>react-data-to-export</code>.
          </p>
        </div>
        <div style={styles.badge}>
          <span>workflow</span>
          <strong>{workflowState}</strong>
        </div>
      </header>

      <section style={styles.panel}>
        <h2>Workflow Driver (@trigo/fsm)</h2>
        <p>
          Click through the state machine to see how @trigo/fsm keeps the UI in
          sync with the CLI flow.
        </p>
        <button style={styles.button} onClick={nextStep}>
          Advance state
        </button>
      </section>

      <section style={styles.grid}>
        <div style={styles.card}>
          <h3>@posthog/icons</h3>
          {iconInfo.Component ? (
            <iconInfo.Component width={48} height={48} color="#f472b6" />
          ) : (
            <p>{iconInfo.name || 'Loading icons...'}</p>
          )}
          <p style={styles.cardHint}>
            Displaying component: {iconInfo.name || 'pending'}
          </p>
        </div>

        <div style={styles.card}>
          <h3>@voiceflow/react-chat</h3>
          <p>First exports discovered:</p>
          <ul>
            {voiceflowExports.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </div>

        <div style={styles.card}>
          <h3>react-data-to-export</h3>
          <p>
            Generate a spreadsheet of the current workflow state and package
            roles.
          </p>
          <ExcelFile
            filename="demo-packages"
            element={<button style={styles.button}>Download Excel</button>}
          >
            <ExcelSheet data={excelData} name="Packages">
              <ExcelColumn label="Package" value="name" />
              <ExcelColumn label="Role" value="role" />
              <ExcelColumn label="Workflow state" value="state" />
            </ExcelSheet>
          </ExcelFile>
        </div>
      </section>
    </div>
  );
}

const styles = {
  shell: {
    padding: '3rem clamp(1.5rem, 5vw, 5rem)'
  },
  header: {
    display: 'flex',
    gap: '2rem',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: '2rem'
  },
  kicker: {
    margin: 0,
    textTransform: 'uppercase',
    letterSpacing: '0.2em',
    fontSize: '0.75rem',
    color: '#94a3b8'
  },
  title: {
    margin: '0.25rem 0',
    fontSize: '2.5rem'
  },
  subtitle: {
    margin: 0,
    maxWidth: '60ch',
    color: '#cbd5f5'
  },
  badge: {
    marginLeft: 'auto',
    background: '#1e293b',
    borderRadius: '0.75rem',
    padding: '0.75rem 1rem',
    textTransform: 'uppercase',
    fontSize: '0.85rem',
    border: '1px solid #334155'
  },
  panel: {
    background: '#111827',
    border: '1px solid #1f2937',
    borderRadius: '1rem',
    padding: '1.5rem',
    marginBottom: '2rem'
  },
  button: {
    background: '#6366f1',
    border: 'none',
    color: '#fff',
    padding: '0.75rem 1.25rem',
    borderRadius: '0.5rem',
    cursor: 'pointer',
    marginTop: '1rem',
    fontSize: '1rem'
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '1.5rem'
  },
  card: {
    background: '#111827',
    border: '1px solid #1f2937',
    borderRadius: '1rem',
    padding: '1.25rem'
  },
  cardHint: {
    marginTop: '1rem',
    color: '#94a3b8'
  }
};

